### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/awards-website#1]
- [ ] Fix "See vote" button
- [ ] Proper display of stuff:
    - [ ] Have table of for each category, and winners select
    - [ ] Query microsoft API for name of the account
    - [ ] Properly handle situations of no vote, or only one.
    - [ ] Category prompts as well
- [ ] Ensure everything works.
